### PR TITLE
(MODULES-10867) Ensure ssh key name is unique based on type, content and description

### PR DESCRIPTION
**Pull request by mdklapwijk**
Allow multiple ssh keys of the same type having the same description.

### CODE REVIEW

**Comment by pmcmaw** [comment]
Hey @mdklapwijk 

I would like to thank you for taking the time to both file a ticket and also create a PR for this issue. 

Would it be possible to address the failing test: `manifests/manage_keys.pp - WARNING: variable not enclosed in {} on line 42`. 

It would also be great if you were able to 
- Add a test to avoid any regressions in the future for this change
- Add some documentation on your change

Many thanks
Paula

**Comment by mdklapwijk** [comment]
Paula, thanks for the suggestion, missed that completely.

**Comment by david22swan** [comment]
@mdklapwijk 
Taking a quick look at this, would just like to reiterate what has already been said.
The change look's good overall but some test coverage and documentation would be needed in order to get it in.

**Comment by mdklapwijk** [comment]
@david22swan, I am not sure how to solve the "Missing base report; Unable to compare commits because the base of the pull request did not upload a coverage report." message/error from codecov.

It seems the only way to solve that is to close this PR and create a new one?

**Comment by sanfrancrisko** [comment]
Hi @mdklapwijk ,

Don't worry about the `codecov` error for the meantime - we'll seek to rectify that at a future date. It appears as though some of our modules do not have a base commit from which `codecov` can compare coverage to. This will likely need some discussion internally on the team as to what is the best point to create that from.

Thanks for the fix - as mentioned, it looks good, however, it would be nice if we could get a test around this new functionality. I've expanded one of the existing tests which should cover us, but feel free to split out or expand further: https://github.com/mdklapwijk-forks/puppetlabs-accounts/pull/1

**Comment by mdklapwijk** [comment]
@sanfrancrisko, thanks. That made it a lot more clear what was expected!

**Review by sanfrancrisko — APPROVED** [review]

**Pull request merged**
