### PR TITLE
(FM-7287) - i18n Process Implemented.

### PR DESCRIPTION
**Pull request by david22swan**
Relevant strings have been decorated with the translate code.
.pot files have been generated and pushed.
Also includes a minor PDK update.

### CODE REVIEW

**Comment by pmcmaw** [comment]
I would recommend until translations come back, introduce unicode or something and implement tests to ensure the whole end to end setup works. You will info on how to do this in the Testing Modules with i18n page.

**Comment by david22swan** [comment]
screen shot 2018-08-22 at 2 56 53 pm

**Comment by david22swan** [comment]
Difference between adhoc and current is just from rebasing onto master following pdksync merge.

**Comment by david22swan** [comment]
screen shot 2018-08-22 at 4 00 44 pm

**Comment by david22swan** [comment]
Updated adhoc run

**Comment by pmcmaw** [comment]
Fantastic changes! 👍

**Pull request merged**
