### PR TITLE
MODULES-10862 add support for authorized_keys file mode

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
@david22swan the travis-ci failure are not due to my change so I'd appreciate if you could still take a look ;)

(you've been helpful in the past, hence the direct ping to you, thanks)

**Comment by david22swan** [comment]
@simondeziel Sorry for the wait.
A fix has been put up for the issue you are experiencing and should be merged soon (#339), so if you rebase onto that you should be fine.
In regards to your pr while the change itself look's good I would like it to have some acceptance test's added to it just for peace of mind.

**Comment by simondeziel** [comment]
> @simondeziel Sorry for the wait.

That was quite fast actually, so thanks!

> A fix has been put up for the issue you are experiencing and should be merged soon (#339), so if you rebase onto that you should be fine.
> In regards to your pr while the change itself look's good I would like it to have some acceptance test's added to it just for peace of mind.

I had already added tests that passed ;)

I'll rebase once #339 is merged and hopefully that will trigger another round of tests. Thanks!

**Comment by simondeziel** [comment]
@david22swan please let me know if I missed anything, thanks!

**Comment by david22swan** [comment]
@simondeziel
Apologies for the wait on the reply again.
Anyway took a quick second look and it still look's good to me. Would still like an acceptance test in addition to the unit one you have added but have decided to go ahead and merge.
Thank you for your work and I hope to see more from you in the future 👍

**Comment by simondeziel** [comment]
@david22swan thanks! Sorry I got confused by acceptance vs unit tests. I'll keep that in mind for future contributions.

**Pull request merged**
