### PR TITLE
(MODULES-10892) Update name.pp

### PR DESCRIPTION
**Pull request by LooOOooM**
bugfix: MODULES-10892
https://tickets.puppetlabs.com/projects/MODULES/issues/MODULES-10892?filter=allissues

### CODE REVIEW

**Comment by sheenaajay** [comment]
Thank you @LooOOooM for submitting the PR.  
The unit test cases failing with the following changes.

`  Invalid user name values
    "1-bad-dude"
      is expected not to match value "1-bad-dude" (FAILED - 1)
    ".hidden"
      is expected not to match value ".hidden" (FAILED - 2)`

Could you please check the following, the updated regex are not satisfying the following username rules.

- Fully numeric usernames and usernames . or .. are also disallowed
- It is not recommended to use usernames beginning with . character as their home directories will be hidden in
- the ls output

**Comment by pmcmaw** [comment]
Hey @LooOOooM :-) 

Just wondering if you have any bandwidth to work on this so we can get it merged :-)

**Comment by LooOOooM** [comment]
I do not see any reasons why 1-bad-dude would be an invalid name :

useradd 1-bad-dude
tail -1 /etc/passwd
1-bad-dude:x:1012:1016::/home/1-bad-dude:/bin/bash

please correct your checks

**Comment by LooOOooM** [comment]
done

**Comment by pmcmaw** [comment]
Hey @LooOOooM  :-) 

I want to thank you for taking the time to make this change however, `1-bad-dude` would be an acceptable username therefore should remain in our tests. The change would be expected to go into the regex pattern to both accommodate for existing tests and also your own use case.

**Comment by LooOOooM** [comment]
sry, I dont get it? is there anything left to do apart from finnaly getting this into production? As of course "1-bad-dude" is a valid username it should get removed out of the test, as the test is a negativ one. The test is failing as the regex is matching "1-bad-dude", However 1-bad-dude is not a fancy name:

```
[root@puppet-centos7-testvm1 ~]# useradd -m 1-bad-dude
[root@puppet-centos7-testvm1 ~]# echo $?
0
[root@puppet-centos7-testvm1 ~]# tail -1 /etc/passwd
1-bad-dude:x:1009:1010::/home/1-bad-dude:/bin/bash
[root@puppet-centos7-testvm1 ~]# su - 1-bad-dude
```

**Comment by pmcmaw** [comment]
@LooOOooM 

Im really sorry, I missed the fact it was a negative test.

Would you mind dropping the test into the valid usernames list here: https://github.com/puppetlabs/puppetlabs-accounts/blob/cc2e789be8bdb93e61f9f18db504318cd20e012f/spec/type_aliases/user_name_spec.rb#L6

Once done I will merge.

**Comment by LooOOooM** [comment]
done

**Comment by pmcmaw** [comment]
Thank you and again I apologize for the oversight on my behalf with the test update.

**Pull request merged**
