### PR TITLE
(MODULES-9697) fix for correct management of sshkey_custom_path

### PR DESCRIPTION
**Pull request by tuxmea**
This PR adds some tests where we see issues at customers:

1. changing group id
1. setting a custom ssh key path

More to come. Waiting for Jenkins pipeline results...

### CODE REVIEW

**Comment by tuxmea** [comment]
> Normally, the key file for a user is owned by that user.

Not when using a global location.
But issue is different: no keyfile created:

    expected `File "/test/sshkeys/hunner".file?` to return true, got false

**Comment by pillarsdotnet** [comment]
> > Normally, the key file for a user is owned by that user.
> 
> Not when using a global location.
> But issue is different: no keyfile created:
> 
> ```
> expected `File "/test/sshkeys/hunner".file?` to return true, got false
> ```

Also see https://tickets.puppetlabs.com/browse/MODULES-9578

**Comment by tuxmea** [comment]
fixes https://tickets.puppetlabs.com/browse/MODULES-9697

**Comment by tuxmea** [comment]
add new parameter in alphabetical order.

**Comment by lionce** [comment]
https://pipelines.puppet.com/team-modules/builds/575113

**Comment by lionce** [comment]
Hello @tuxmea ,

Looks good to me. 👍 Thank you for this contribution! 

Cheers!

**Pull request merged**
